//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task5.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SortedArrays
    {
        public int iSortedArrayId { get; set; }
        public int iInputArrayId { get; set; }
        public double fSortingTime { get; set; }
        public string vcSorterName { get; set; }
        public string vcSortedArrayContent { get; set; }
    
        public virtual InputArrays InputArrays { get; set; }
    }
}
