//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task5.Forms.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessagesMainFormView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesMainFormView() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Task5.Forms.Localization.MessagesMainFormView", typeof(MessagesMainFormView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Array initialization.
        /// </summary>
        internal static string ArrayInitializationText {
            get {
                return ResourceManager.GetString("ArrayInitializationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Array legth.
        /// </summary>
        internal static string ArrayLegthText {
            get {
                return ResourceManager.GetString("ArrayLegthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error in array inserting into database..
        /// </summary>
        internal static string DatabaseArrayInsertingErrorText {
            get {
                return ResourceManager.GetString("DatabaseArrayInsertingErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Database connection.
        /// </summary>
        internal static string DatabaseConnection {
            get {
                return ResourceManager.GetString("DatabaseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The required database does not exist.
        /// </summary>
        internal static string DatabaseDosentExistText {
            get {
                return ResourceManager.GetString("DatabaseDosentExistText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Database saving.
        /// </summary>
        internal static string DatabaseSavingCaption {
            get {
                return ResourceManager.GetString("DatabaseSavingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        internal static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could not find selected language in current languages files.
        /// </summary>
        internal static string LanguageNotFoundText {
            get {
                return ResourceManager.GetString("LanguageNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you want to add this array to database? If you don&apos;t add array to database than information about sorting process will not be inserted to database after sorting..
        /// </summary>
        internal static string SaveArrayDialogText {
            get {
                return ResourceManager.GetString("SaveArrayDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  finished sorting.
        /// </summary>
        internal static string SorterFinishedSortingText {
            get {
                return ResourceManager.GetString("SorterFinishedSortingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sorting aborted.
        /// </summary>
        internal static string SortingAbortedText {
            get {
                return ResourceManager.GetString("SortingAbortedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sorting complete.
        /// </summary>
        internal static string SortingCompleteText {
            get {
                return ResourceManager.GetString("SortingCompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot perform this action while sorting is started.
        /// </summary>
        internal static string SortingIsStartedWarningText {
            get {
                return ResourceManager.GetString("SortingIsStartedWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sorting process.
        /// </summary>
        internal static string SortingProcessCaption {
            get {
                return ResourceManager.GetString("SortingProcessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sorting started....
        /// </summary>
        internal static string SortingStartedText {
            get {
                return ResourceManager.GetString("SortingStartedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Successfully initialized array.
        /// </summary>
        internal static string SuccessfullyInitializedArrayText {
            get {
                return ResourceManager.GetString("SuccessfullyInitializedArrayText", resourceCulture);
            }
        }
    }
}
