//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task5.Forms.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessagesRandomArrayCreationInDatabaseForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesRandomArrayCreationInDatabaseForm() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Task5.Forms.Localization.MessagesRandomArrayCreationInDatabaseForm", typeof(MessagesRandomArrayCreationInDatabaseForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimum value cannot be equal or greater than maximum value..
        /// </summary>
        internal static string ArrayRangeValidationErrorText {
            get {
                return ResourceManager.GetString("ArrayRangeValidationErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Random array was successfully created.
        /// </summary>
        internal static string ArraySuccessfullyCreatedText {
            get {
                return ResourceManager.GetString("ArraySuccessfullyCreatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Random array wasn&apos;t successfully created. Try again..
        /// </summary>
        internal static string ArrayUnsuccessfullyCreatedText {
            get {
                return ResourceManager.GetString("ArrayUnsuccessfullyCreatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter a valid integer and try again.
        /// </summary>
        internal static string ConvertToIntegerErrorText {
            get {
                return ResourceManager.GetString("ConvertToIntegerErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Database connection.
        /// </summary>
        internal static string DatabaseConnectionText {
            get {
                return ResourceManager.GetString("DatabaseConnectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The required database does not exist.
        /// </summary>
        internal static string DatabaseDosentExistText {
            get {
                return ResourceManager.GetString("DatabaseDosentExistText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        internal static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Operation result.
        /// </summary>
        internal static string OperationResultText {
            get {
                return ResourceManager.GetString("OperationResultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rows and columns cannot be greater than 1000 or less than 1. Try again..
        /// </summary>
        internal static string RowsAndColumnsValidationErrorText {
            get {
                return ResourceManager.GetString("RowsAndColumnsValidationErrorText", resourceCulture);
            }
        }
    }
}
